# Generated by Django 3.2.6 on 2021-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroSite', '0002_delivereddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='returndb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceno', models.CharField(blank=True, max_length=100, null=True)),
                ('orderid', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=200, null=True)),
                ('custname', models.CharField(blank=True, max_length=200, null=True)),
                ('shippingname', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('custaddress', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('custmob', models.CharField(blank=True, max_length=200, null=True)),
                ('altmobno', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
