# Generated by Django 3.2.6 on 2021-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroSite', '0003_returndb'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivereddb',
            name='driverid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returndb',
            name='driverid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
