# Generated by Django 3.2.6 on 2021-10-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroSite', '0004_auto_20211008_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivereddb',
            old_name='driverid',
            new_name='Drivercode',
        ),
        migrations.RenameField(
            model_name='returndb',
            old_name='driverid',
            new_name='Drivercode',
        ),
    ]
