# Generated by Django 3.2.6 on 2021-10-11 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroSite', '0005_auto_20211008_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivereddb',
            name='date_of_delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='delivereddb',
            name='productcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivereddb',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delivereddb',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returndb',
            name='Order_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returndb',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
