# Generated by Django 3.2.6 on 2021-10-12 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroSite', '0006_auto_20211011_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivereddb',
            old_name='username',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='returndb',
            old_name='username',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='returndb',
            name='Order_Id',
        ),
        migrations.AddField(
            model_name='returndb',
            name='date_of_return',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='returndb',
            name='productcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='returndb',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
