# Generated by Django 3.2.6 on 2021-10-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroSite', '0007_auto_20211012_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndb',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
