# Generated by Django 3.2.6 on 2021-09-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregister',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
