# Generated by Django 3.2.6 on 2021-09-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroApp', '0002_adminregister_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregister',
            old_name='name',
            new_name='names',
        ),
    ]
