# Generated by Django 3.2.6 on 2021-10-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroApp', '0005_taskdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdb',
            name='userid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
