# Generated by Django 3.2.6 on 2021-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroApp', '0006_taskdb_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregister',
            name='userid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
