# Generated by Django 3.2.6 on 2021-10-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroApp', '0007_driverregister_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdb',
            name='Lattitude',
        ),
        migrations.RemoveField(
            model_name='taskdb',
            name='Longitude',
        ),
    ]
