# Generated by Django 3.2.6 on 2021-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveroApp', '0008_auto_20211012_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdb',
            name='Clientname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
